### ISSUE TITLE
Error log

### ISSUE THREAD

**Issue by pbardou** [dwbellott/shims2_assembly_pipeline#2]
Hello,

It seems that I have a BESST error (perhaps wrong version), but I can't find the run command in the perl file...
I copied/pasted the shims2 log, do you have an idea about this error?

```
Number of initial contigs: 5
Estimating insert size from 309061 mappings with quality over --min_mapq 11.
Choosing mode: 200
mu_adjusted:199.4276208512161, sigma_adjusted:10.019833416720692, skewness_adjusted:-0.006937371152777619
Creating contig graph with library:  TEST_SHIMS2/scaffolding.srt.bam
Traceback (most recent call last):
  File "BESST/runBESST", line 431, in <module>
    main(args)
  File "BESST/runBESST", line 182, in main
    (G, G_prime) = CG.PE(Contigs, Scaffolds, Information, C_dict, param, small_contigs, small_scaffolds, bam_file)      #Create graph, single out too short contigs/scaffolds and store them in F
  File "/save/sigenae/Philippe/shims2_assembly_pipeline/BESST/BESST/CreateGraph.py", line 79, in PE
    InitializeGraph(Scaffolds, G, Information)
  File "/save/sigenae/Philippe/shims2_assembly_pipeline/BESST/BESST/CreateGraph.py", line 715, in InitializeGraph
    graph.node[(scaffold_, 'L')]['length'] = dict_with_scaffolds[scaffold_].s_length
AttributeError: 'Graph' object has no attribute 'node'
Scaffolding Failed
```

Any help would be appreciated
Thanks
Regards

**Comment by dwbellott** [comment]
This looks like an error in BESST. I'm using version 2.2.8. Which BESST version do you have installed? Which version of python?

**Comment by pbardou** [comment]
Thanks for your message.
I'm using BESST 2.2.8 also and python 3.6.3...

**Comment by dwbellott** [comment]
I suspect your version of python is too old. BESST depends on [networkx](https://networkx.org/documentation/latest/install.html), which requires python 3.7, 3.8, or 3.9. Since you're getting an error about graphs and nodes, I suspect that's causing this problem.
